# Datos censales

En este notebook, se tomarán las bases de datos de los censos correspondientes a los años 2017 y 2024. Se juntarpan por comuna, y se interpolarán para hacer una estimación de la población aproximada durante los años intermedios.

In [14]:
import pandas as pd

In [15]:
# Función para manejar los nombres de las comunas

def limpiar_comuna(nombre):
    nombre = nombre.strip().title()
    nombre = nombre.replace('Nunoa', 'Ñuñoa')
    nombre = nombre.replace('Penalolen', 'Peñalolén')
    nombre = nombre.replace('Peñalolen', 'Peñalolén')
    nombre = nombre.replace('Conchali', 'Conchalí')
    nombre = nombre.replace('Estacion Central', 'Estación Central')
    nombre = nombre.replace('San Joaquin', 'San Joaquín')
    nombre = nombre.replace('San Jose De Maipo', 'San José de Maipo')
    nombre = nombre.replace('San Ramon', 'San Ramón')
    nombre = nombre.replace('Maipu', 'Maipú')
    nombre = nombre.replace('Alhue', 'Alhué')
    nombre = nombre.replace('Curacavi', 'Curacaví')
    if 'Desconocido' in nombre or 'Total' in nombre:
        return None
    return nombre

# Base de datos 2017

In [16]:
df_2017 = pd.read_excel('Poblacion-censada-y-residentes-habituales-Censo-2017.xlsx', sheet_name=2, header=3)
df_2017.reset_index(drop=True, inplace=True)
df_2017.head()

,Código región,Región,Código provincia,Provincia,Código comuna,Comuna,Población censada,Residentes habituales
0,0,País,0.0,País,0.0,País,17574003.0,17327192.0
1,1,Tarapacá,11.0,Iquique,1101.0,Iquique,191468.0,191824.0
2,1,Tarapacá,11.0,Iquique,1107.0,Alto Hospicio,108375.0,106596.0
3,1,Tarapacá,14.0,Del Tamarugal,1401.0,Pozo Almonte,15711.0,13942.0
4,1,Tarapacá,14.0,Del Tamarugal,1402.0,Camiña,1250.0,1217.0

In [17]:
# Filtramos para la región metropolitana

df_2017 = df_2017[df_2017['Región'] == 'Metropolitana De Santiago']
df_2017 = df_2017.reset_index(drop=True)
df_2017.head()

,Código región,Región,Código provincia,Provincia,Código comuna,Comuna,Población censada,Residentes habituales
0,13,Metropolitana De Santiago,131.0,Santiago,13101.0,Santiago,404495.0,411183.0
1,13,Metropolitana De Santiago,131.0,Santiago,13102.0,Cerrillos,80832.0,79842.0
2,13,Metropolitana De Santiago,131.0,Santiago,13103.0,Cerro Navia,132622.0,131433.0
3,13,Metropolitana De Santiago,131.0,Santiago,13104.0,Conchalí,126955.0,125278.0
4,13,Metropolitana De Santiago,131.0,Santiago,13105.0,El Bosque,162505.0,161571.0

In [18]:
df_2017 = df_2017[['Comuna', 'Residentes habituales']].copy()
df_2017.rename(columns={'Residentes habituales': 'Población 2017'}, inplace=True)
df_2017.reset_index(drop=True, inplace=True)
df_2017.head()

        Comuna  Población 2017
0     Santiago        411183.0
1    Cerrillos         79842.0
2  Cerro Navia        131433.0
3     Conchalí        125278.0
4    El Bosque        161571.0

# Base de datos 2024

In [19]:
df_2024 = pd.read_excel('D1_Poblacion-censada-por-sexo-y-edad-en-grupos-quinquenales.xlsx', sheet_name=2, header=3)
df_2024.reset_index(drop=True, inplace=True)
df_2024.head()

,Código región,Región,Código provincia,Provincia,Código comuna,Comuna,Población censada,Hombres,Mujeres,Razón hombre-mujer
0,0,País,0.0,País,0.0,País,18480432.0,8967033.0,9513399.0,94.3
1,15,Arica y Parinacota,151.0,Arica,15101.0,Arica,241653.0,118844.0,122809.0,96.8
2,15,Arica y Parinacota,151.0,Arica,15102.0,Camarones,861.0,430.0,431.0,99.8
3,15,Arica y Parinacota,152.0,Parinacota,15201.0,Putre,1547.0,846.0,701.0,120.7
4,15,Arica y Parinacota,152.0,Parinacota,15202.0,General Lagos,508.0,261.0,247.0,105.7

In [20]:
df_2024 = df_2024[df_2024['Región'] == 'Metropolitana de Santiago']
df_2024 = df_2024.reset_index(drop=True)
df_2024.head()

,Código región,Región,Código provincia,Provincia,Código comuna,Comuna,Población censada,Hombres,Mujeres,Razón hombre-mujer
0,13,Metropolitana de Santiago,131.0,Santiago,13101.0,Santiago,438856.0,223237.0,215619.0,103.5
1,13,Metropolitana de Santiago,131.0,Santiago,13102.0,Cerrillos,85041.0,41216.0,43825.0,94.0
2,13,Metropolitana de Santiago,131.0,Santiago,13103.0,Cerro Navia,127250.0,62329.0,64921.0,96.0
3,13,Metropolitana de Santiago,131.0,Santiago,13104.0,Conchalí,121587.0,59122.0,62465.0,94.6
4,13,Metropolitana de Santiago,131.0,Santiago,13105.0,El Bosque,155257.0,75720.0,79537.0,95.2

In [21]:
df_2024 = df_2024[['Comuna', 'Población censada']].copy()
df_2024['Comuna'] = df_2024['Comuna'].apply(limpiar_comuna)
df_2024.rename(columns={'Población censada': 'Población 2024'}, inplace=True)
df_2024.head()

        Comuna  Población 2024
0     Santiago        438856.0
1    Cerrillos         85041.0
2  Cerro Navia        127250.0
3     Conchalí        121587.0
4    El Bosque        155257.0

# Merge censo 2017 - 2024

In [22]:
df_censo = pd.merge(df_2017, df_2024, on='Comuna', how='inner')
df_censo

                 Comuna  Población 2017  Población 2024
0              Santiago        411183.0        438856.0
1             Cerrillos         79842.0         85041.0
2           Cerro Navia        131433.0        127250.0
3              Conchalí        125278.0        121587.0
4             El Bosque        161571.0        155257.0
5      Estación Central        139257.0        181049.0
6            Huechuraba         97829.0        101808.0
7         Independencia         98513.0        116943.0
8           La Cisterna         89204.0        103157.0
9            La Florida        364039.0        374836.0
10            La Granja        115641.0        112022.0
11           La Pintana        176188.0        175421.0
12             La Reina         91717.0         89870.0
13           Las Condes        287023.0        296134.0
14         Lo Barnechea        103301.0        112620.0
15            Lo Espejo         98025.0         87295.0
16             Lo Prado         95325.0         91290.0
17                Macul        115802.0        123800.0
18                Maipú        517384.0        503635.0
19                Ñuñoa        205602.0        241467.0
20  Pedro Aguirre Cerda        100036.0         96062.0
21            Peñalolén        239615.0        236478.0
22          Providencia        136279.0        143974.0
23             Pudahuel        225447.0        227820.0
24            Quilicura        208460.0        205624.0
25        Quinta Normal        109456.0        129351.0
26             Recoleta        155779.0        154615.0
27                Renca        145359.0        143622.0
28          San Joaquín         93710.0         95602.0
29           San Miguel        105879.0        150829.0
30            San Ramón         81817.0         76002.0
31             Vitacura         82858.0         86420.0
32          Puente Alto        562136.0        568086.0
33               Pirque         26217.0         29060.0
34               Colina        143674.0        173293.0
35                Lampa        100785.0        145160.0
36               Tiltil         18769.0         19742.0
37         San Bernardo        298699.0        306371.0
38                 Buin         95653.0        116969.0
39      Calera De Tango         25230.0         25491.0
40                Paine         71872.0         78828.0
41            Melipilla        122274.0        136325.0
42                Alhué          6007.0          7768.0
43             Curacaví         32068.0         35165.0
44          María Pinto         13341.0         15352.0
45            San Pedro         10156.0         11108.0
46            Talagante         73234.0         76429.0
47             El Monte         35552.0         37497.0
48        Padre Hurtado         62601.0         81243.0
49             Peñaflor         89419.0         94402.0

Para ver si estos datos tienen sentido, hagamos la suma por columnas a ambos años:

In [23]:
# Sumar la columna de población 2017
total_2017 = df_censo['Población 2017'].sum()
print(f"Población total 2017 RM: {total_2017:,.0f}")

# Sumar la columna de población 2024
total_2024 = df_censo['Población 2024'].sum()
print(f"Población total 2024 RM: {total_2024:,.0f}")

Población total 2017 RM: 6,976,539
Población total 2024 RM: 7,344,026

# Interpolación: estimación de habitantes por comuna entre el período 2017-2024

In [24]:

# Consulta a la IA generativa: '¿Cómo puedo estimar la población entre un período de años teniendo la población de los 
# dos años "extremos" calculados?'

años = list(range(2017, 2025)) 
comunas = df_censo['Comuna']

rows = []

for i, row in df_censo.iterrows():
    pop_2017 = row['Población 2017']
    pop_2024 = row['Población 2024']
    # Interpolación lineal para cada año
    for j, año in enumerate(años):
        pop_interp = pop_2017 + (pop_2024 - pop_2017) * j / (2024 - 2017)
        rows.append({'Comuna': row['Comuna'], 'Año': año, 'Población': pop_interp})

df_interpolado = pd.DataFrame(rows)

df_interpolado.head(10)

      Comuna   Año      Población
0   Santiago  2017  411183.000000
1   Santiago  2018  415136.285714
2   Santiago  2019  419089.571429
3   Santiago  2020  423042.857143
4   Santiago  2021  426996.142857
5   Santiago  2022  430949.428571
6   Santiago  2023  434902.714286
7   Santiago  2024  438856.000000
8  Cerrillos  2017   79842.000000
9  Cerrillos  2018   80584.714286

In [25]:
df_interpolado.to_csv('estimacion_poblacion_por_comunas.csv', index=False)